# fly.toml app configuration file generated for medi-control on 2025-10-13T20:42:02-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medi-control'
primary_region = 'gru'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_NAME="MediControl"
  APP_ENV = "production"
  APP_DEBUG=false
  APP_TIMEZONE="America/Sao_Paulo"
  APP_URL="https://medi-control.fly.dev"

  APP_LOCALE="pt_BR"
  APP_FALLBACK_LOCALE="pt"
  APP_FAKER_LOCALE="pt_BR"

  APP_MAINTENANCE_DRIVER="file"
  # APP_MAINTENANCE_STORE=database

  DB_CONNECTION="pgsql"
  DB_HOST="medi-control-db.internal"
  DB_PORT="5432"
  DB_DATABASE="postgres"
  DB_USERNAME="postgres"

  CACHE_STORE="database"
  DB_CACHE_CONNECTION="pgsql"
  QUEUE_CONNECTION="database"

  SESSION_DRIVER="database"
  SESSION_LIFETIME=120
  SESSION_ENCRYPT="false"
  SESSION_PATH="/"
  SESSION_DOMAIN="null"

  PHP_CLI_SERVER_WORKERS=4

  BCRYPT_ROUNDS=12

  LOG_CHANNEL="stack"
  LOG_LEVEL="debug"

  VITE_APP_NAME="${APP_NAME}"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "sh -c 'php artisan migrate --force && php artisan optimize'"
